#cloud-config

# 0-init.yml (cloud-init)
# Purpose: Minimal initialization during provisioning on providers that support cloud-init.
# - Creates default 'ubuntu' user with SSH key
# - Installs minimal tooling (git, make, curl, wget, unzip, vim)
# - Clones the setup repo to /home/ubuntu/server-setup
# Follow-up configuration is performed via repository scripts after SSH.

users:
  - name: ubuntu
    groups: [users, admin, sudo]
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ${ssh_public_key} # Replace this with your SSH public key

package_update: true
package_upgrade: true

packages:
  # Minimal tooling to fetch and run the setup repo (security/Docker handled later)
  - git
  - make
  - curl
  - wget
  - unzip
  - vim

# Minimal SSH hardening (do not change port here to avoid lockout)
write_files:
  - path: /etc/ssh/sshd_config.d/99-cloud-init.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      KbdInteractiveAuthentication no
      ChallengeResponseAuthentication no

runcmd:
  - [ bash, -lc, 'cd /home/ubuntu && git clone https://github.com/rfpdl/cloud-infra-setup.git server-setup' ]
  - [ chown, -R, ubuntu:ubuntu, /home/ubuntu/server-setup ]
  - [ bash, -lc, 'chmod +x /home/ubuntu/server-setup/*.sh || true' ]
  # Next steps are performed manually after SSH:
  # 1) sudo bash 1-server-hardening.sh (security hardening: SSH, fail2ban, UFW)
  # 2) sudo bash 2-server-bootstrap.sh (Docker Engine + Compose v2)
  # 3) sudo bash 3A-control-plane.commands.sh or 3B-worker.commands.sh
  # 4) sudo bash test/control-plane.test.sh or test/worker.test.sh
  - [ systemctl, restart, sshd ]
  - [ bash, -lc, 'touch /var/lib/cloud/instance/cloud-config-finished' ]
  - [ bash, -lc, 'echo "$(date): Cloud-init 0-init.yml completed - repo cloned to /home/ubuntu/server-setup" > /var/log/cloud-config-setup.log' ]

final_message: |
  Repository cloned to /home/ubuntu/server-setup

  Next steps:
  1. SSH to server: ssh ubuntu@YOUR_SERVER_IP
  2. cd /home/ubuntu/server-setup
  3. cp .env.example .env && vim .env
  4. make control-plane    # or make worker

# No automatic reboot — scripts handle services and restarts as needed
