name: YAML Lint

on:
  push:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - '.yamllint'
      - '.github/workflows/yaml-lint.yml'
  pull_request:
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - '.yamllint'
      - '.github/workflows/yaml-lint.yml'

jobs:
  yamllint:
    name: Run yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Lint YAML files
        run: |
          yamllint -c .yamllint .
